apiVersion: 1

datasources:
  - name: InfluxDB-PowerFlow
    uid: powerflow-influxdb-ds
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: powerflow-org
      defaultBucket: powerflow
      tlsSkipVerify: true
    secureJsonData:
      token: powerflow-super-secret-token-2026
    editable: true